name: "deepBlink"
comments: "This is my shiny comment!"
savedir: "/path/where/model/is/saved/"
use_wandb: True
dataset: "SpotsDataset"
dataset_args:
    version: "/path/to/datset/file.npz"
    cell_size: 4
    flip: False
    illuminate: False
    rotate: False
    gaussian_noise: False
    translate: False
model: "SpotsModel"
network: "resnet"
network_args:
    # dropout: 0.2
loss: "binary_crossentropy"
optimizer: "adam"
train_args:
    batch_size: 1
    epochs: 200
    learning_rate: 1e-4
    # pretrained: None
