# Storage of pip dependencies across builds
cache: pip

# Matrix for all supportd python versions on linux, windows, osx
matrix:
  include:
    - name: Python 3.8.1 on Ubuntu 16.04 (Xenial Xerus)
      env:
        - TOXENV=py38
      language: python
      os: linux
      dist: xenial
      python: 3.8.1

    - name: Python 3.7.6 on Ubuntu 16.04 (Xenial Xerus)
      env:
        - TOXENV=py37
      language: python
      os: linux
      dist: xenial
      python: 3.7.6

    - name: Python 3.6.8 on Ubuntu 16.04 (Xenial Xerus)
      env:
        - TOXENV=py36
      language: python
      os: linux
      dist: xenial
      python: 3.6.8

    - name: Python 3.8.1 on Windows 10 (64-bit)
      env:
        - TOXENV=py38
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - choco install python --version 3.8.1

    - name: Python 3.7.6 on Windows 10 (64-bit)
      env:
        - TOXENV=py37
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - choco install python --version 3.7.6

    - name: Python 3.6.8 on Windows 10 (64-bit)
      env:
        - TOXENV=py36
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - choco install python --version 3.6.8

# Install the latest requirements
install:
  - python -m pip install --upgrade tox virtualenv pip setuptools six codecov

# Run tox
script:
  - tox -v

# Upload test coverages to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Expand tox information on failure
after_failure:
  - more .tox/*/log/* | cat

# Email settings
notifications:
  email:
    on_success: never
    on_failure: always
