[tox]
envlist =
    py{311,312,313},
    safety,
    style
skip_missing_interpreters = true

[testenv]
deps =
    hypothesis
    matplotlib
    numpy
    pandas
    pytest
    pytest-cov
    pyyaml
    scikit-image
    tensorflow
    keras
    wandb
commands =
    py.test --cov=deepblink --cov-report=xml {posargs:tests}

[testenv:safety]
deps =
    bandit
skip_install = true
commands =
    bandit -r deepblink -q

[testenv:style]
deps =
    ruff>=0.4
skip_install = true
commands =
    ruff check deepblink
    ruff format --check deepblink
