package:
    name: "deepblink"
    version: 0.2.0
source:
    path: ..

build:
    build: 1
    preserve_egg_dir: True
    script: python -m pip install --no-deps --ignore-installed .
    entry_points:
      - deepblink = deepblink.cli:main

requirements:
    build:
      - python>=3.11
      - pip
      - setuptools
    run:
      - python>=3.11,<3.14
      - keras>=3.8
      - matplotlib>=3.8
      - numpy>=2.0
      - pandas>=2.2
      - pyyaml
      - requests
      - scikit-image>=0.22
      - scipy>=1.11
      - tensorflow>=2.16

test:
  commands:
    - deepblink --help
  imports:
    - deepblink
