package:
    name: "deepblink"
    version: 0.1.4
source:
    path: ..

build:
    build: 1
    preserve_egg_dir: True
    script: python -m pip install --no-deps --ignore-installed .
    entry_points:
      - deepblink = deepblink.cli:main

requirements:
    build:
      - python>=3.6,<3.9
      - pip
      - setuptools
    run:
      - python>=3.7,<3.11
      - matplotlib>=3.0.0
      - requests>=2.0.0
      - numpy>=1.17.0
      - pandas>=1.0.0
      - pillow>=7.0.0
      - scikit-image>=0.16.2
      - scipy>=1.4.0
      - tensorflow>=2.0

test:
  commands:
    - deepblink --help
  imports:
    - deepblink
