name: main

on:
  pull_request:
  push:
    branches: [master]

jobs:
  # Unittests on windows/ubuntu across python versions
  unittest:
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install tox
      - name: run tox
        run: tox -e py
      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # Lint and style checks
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: run tox style
        run: tox -e style

  # Security checks
  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: run tox safety
        run: tox -e safety
